GET http://localhost:3000


###
POST http://localhost:3000/api/register
Content-Type: application/json

 {
    "name": "shubham",
    "email": "shubham56@example.com",
    "password": "Passwor@d123"
 }
